baseURL = 'https://nreckle.github.io/blog/'
languageCode = 'en-us'
title = 'Ben Blog'
theme="typo"

[params]
  author = "Ben"
  description = "A blog about various topics."
  customCSS = ["css/custom.css"]

# Intro on main page, content in markdown
homeIntroTitle = 'Hi!'
homeIntroContent = """
I am a Software Engineer with a strong foundation in computer science and a passion for solving complex problems.
"""

# Main menu pages
[[params.menu]]
name = "home"
url = "/blog/"

[[params.menu]]
name = "posts"
url = "/blog/posts"

[[params.menu]]
name = "about"
url = "/blog/about"

[markup]
  [markup.highlight]
    style = "monokai"
    lineNos = true

[taxonomies]
  category = "categories"
  tag = "tags"
