baseURL = 'https://nreckle.github.io/'
languageCode = 'en-us'
title = 'Ben Blog'
theme="typo"

[params]
  author = "Ben"
  description = "A blog about various topics."
  customCSS = ["css/custom.css"]

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 1
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 2
